[package]
name = "pgx"
version = "0.1.0"
authors = ["Eric B. Ridge <eebbrr@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["rlib"]

[features]
default = []
pg10 = ["pgx-pg-sys/pg10"]
pg11 = ["pgx-pg-sys/pg11"]
pg12 = ["pgx-pg-sys/pg12"]

[dependencies]
pgx-macros = { path = "../pgx-macros/" }
pgx-pg-sys = { path = "../pgx-pg-sys" }
time = {version = "0.2.6", features = ["serde"] }
enum-primitive-derive = "0.1.2"
lazy_static = "1.4.0"
num-traits = "0.2.10"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.46"
serde_cbor = "0.11.1"

