[package]
name = "pgx"
version = "0.0.15"
authors = ["ZomboDB, LLC <zombodb@gmail.com>"]
edition = "2018"
license = "MIT"
description = "pgx:  A Rust framework for creating Postgres extensions"
homepage = "https://github.com/zombodb/pgx"
repository = "https://github.com/zombodb/pgx"
documentation = "https://docs.rs/pgx"
readme = "../README.md"

[lib]
crate-type = [ "rlib" ]

[features]
default = [ ]
pg10 = [ "pgx-pg-sys/pg10" ]
pg11 = [ "pgx-pg-sys/pg11" ]
pg12 = [ "pgx-pg-sys/pg12" ]

[package.metadata.docs.rs]
features = ["pg12"]
no-default-features = true

[dependencies]
enum-primitive-derive = "0.2.1"
num-traits = "0.2.12"
seahash = "4.0.1"
pgx-macros = { path = "../pgx-macros/", version= "^0.0.15"}
pgx-pg-sys = { path = "../pgx-pg-sys", version= "^0.0.15"}
serde = { version = "1.0.116", features = [ "derive" ] }
serde_cbor = "0.11.1"
serde_json = "1.0.57"
time = "0.2.20"
atomic-traits = "0.2.0"
heapless = { git = "https://github.com/japaric/heapless" } 
hash32 = "0.1.1"
uuid = { version = "0.8.1", features = [ "v4" ] } 
once_cell = "1.4.1"
bitflags = "1.2.1"

