[package]
name = "pgx"
version = "0.0.2"
authors = ["ZomboDB, LLC <zombodb@gmail.com>"]
edition = "2018"
license = "MIT"
description = "pgx:  A Rust framework for creating Postgres extensions"
homepage = "https://github.com/zombodb/pgx"
repository = "https://github.com/zombodb/pgx"
documentation = "https://docs.rs/pgx"
readme = "../README.md"

[lib]
crate-type = [ "rlib" ]

[features]
default = [ ]
pg10 = [ "pgx-pg-sys/pg10" ]
pg11 = [ "pgx-pg-sys/pg11" ]
pg12 = [ "pgx-pg-sys/pg12" ]

[dependencies]
enum-primitive-derive = "0.1.2"
lazy_static = "1.4.0"
num-traits = "0.2.10"
pgx-macros = { path = "../pgx-macros/", version="0.0.2" }
pgx-pg-sys = { path = "../pgx-pg-sys", version="0.0.2" }
serde = { version = "1.0.104", features = [ "derive" ] }
serde_cbor = "0.11.1"
serde_json = "1.0.46"
time = "0.2.7"
