[package]
name = "pgx-macros"
version = "0.1.0"
authors = [ "Eric B. Ridge <eebbrr@gmail.com>" ]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
pgx-utils = { path = "../pgx-utils" }
proc-macro2 = "1.0.6"
quote = "1.0.2"
regex = "1.3.1"
syn = { version = "1.0.5", features = [ "extra-traits", "full", "fold", "parsing" ] }
unescape = "0.1.0"
