[package]
name = "pgx-macros"
version = "0.0.1"
authors = ["ZomboDB, LLC <zombodb@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Proc Macros for 'pgx'"
homepage = "https://github.com/zombodb/pgx/pg-macros"
repository = "https://github.com/zombodb/pgx/pg-macros"
documentation = "https://docs.rs/pgx-macros"
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
pgx-utils = { path = "../pgx-utils" }
proc-macro2 = "1.0.6"
quote = "1.0.2"
regex = "1.3.1"
syn = { version = "1.0.5", features = [ "extra-traits", "full", "fold", "parsing" ] }
unescape = "0.1.0"
