[package]
name = "cargo-pgx"
version = "0.0.2"
authors = ["ZomboDB, LLC <zombodb@gmail.com>"]
edition = "2018"
license = "MIT"
description = "cargo subcommand for 'pgx' to make Postgres extension development easy"
homepage = "https://github.com/zombodb/pgx/cargo-pgx"
repository = "https://github.com/zombodb/pgx/cargo-pgx"
documentation = "https://docs.rs/pgx-tests"
readme = "README.md"

[dependencies]
clap = { version = "2.33.0", features = [ "yaml" ] }
colored = "1.9.1"
pgx-utils = { path = "../pgx-utils", version="0.0.1" }
proc-macro2 = { version = "1.0.6", features = [ "span-locations" ] }
quote = "1.0.2"
rayon = "1.3.0"
regex = "1.3.1"
syn = { version = "1.0.5", features = [ "extra-traits", "full", "fold", "parsing" ] }
unescape = "0.1.0"
