[package]
name = "pgx-tests"
version = "0.0.1"
authors = ["ZomboDB, LLC <zombodb@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Test framework for 'pgx'-based Postgres extensions"
homepage = "https://github.com/zombodb/pgx/pg-tests"
repository = "https://github.com/zombodb/pgx/pg-tests"
documentation = "https://docs.rs/pgx-tests"
readme = "README.md"

[lib]
crate-type = [ "cdylib", "rlib" ]

[features]
default = [ ]
pg10 = [ "pgx/pg10" ]
pg11 = [ "pgx/pg11" ]
pg12 = [ "pgx/pg12" ]
pg_test = [ ]

[dependencies]
colored = "1.9.1"
lazy_static = "1.4.0"
libc = "0.2.66"
pgx = { path = "../pgx", default-features = false, version="0.0.1" }
pgx-macros = { path = "../pgx-macros", version="0.0.1" }
postgres = "0.17.0"
regex = "1.3.1"
serde = "1.0.104"
serde_json = "1.0.46"
shutdown_hooks = "0.1.0"
time = "0.2.7"
