[package]
name = "pgx-utils"
version = "0.0.15"
authors = ["ZomboDB, LLC <zombodb@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Utility functions for 'pgx'"
homepage = "https://github.com/zombodb/pgx/pg-utils"
repository = "https://github.com/zombodb/pgx/pg-utils"
documentation = "https://docs.rs/pgx-utils"
readme = "README.md"

[dependencies]
colored = "2.0.0"
dirs = "3.0.1"
proc-macro2 = "1.0.21"
quote = "1.0.7"
regex = "1.3.9"
serde = "1.0.116"
serde_derive = "1.0.116"
syn = { version = "1.0.41", features = [ "extra-traits", "full", "fold", "parsing" ] }
toml = "0.5.6"
unescape = "0.1.0"
