[package]
name = "pgx-utils"
version = "0.1.0"
authors = [ "Eric B. Ridge <eebbrr@gmail.com>" ]
edition = "2018"

[dependencies]
proc-macro2 = "1.0.6"
quote = "1.0.2"
syn = { version = "1.0.5", features = [ "extra-traits", "full", "fold", "parsing" ] }
unescape = "0.1.0"
