[package]
name = "pgx-utils"
version = "0.0.3"
authors = ["ZomboDB, LLC <zombodb@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Utility functions for 'pgx'"
homepage = "https://github.com/zombodb/pgx/pg-utils"
repository = "https://github.com/zombodb/pgx/pg-utils"
documentation = "https://docs.rs/pgx-utils"
readme = "README.md"

[dependencies]
proc-macro2 = "1.0.6"
quote = "1.0.2"
syn = { version = "1.0.5", features = [ "extra-traits", "full", "fold", "parsing" ] }
unescape = "0.1.0"
