name: test

on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master

jobs:
  test:

    #runs-on: ${{ matrix.os }}
    runs-on: self-hosted

    strategy:
      matrix:
        version: [10, 11, 12]

    steps:
    - uses: actions/checkout@v1

    # which host are we running on?
    - name: hostname
      run: hostname

    # Ubuntu system dependencies required to build Postgres from sources
    - name: install postgres build dependencies
      run: sudo apt install -y bison flex zlib1g zlib1g-dev pkg-config libssl-dev

    # install sccache
    - name: install sccache
      run: if [ ! -f ~/.cargo/bin/sccache ]; then cargo install sccache --force; fi

    # install our cargo subcomment
    - name: install cargo pgx
      run: cd cargo-pgx && RUSTC_WRAPPER=sccache CARGO_TARGET_DIR=/tmp/pgx-build-cargo-pgx/ cargo install --path . --force

    # test our code
    - name: cargo test
      run: RUSTC_WRAPPER=sccache RUST_BACKTRACE=1 CARGO_TARGET_DIR=/tmp/pgx-build-v${{ matrix.version }} cargo test --target-dir /tmp/pgx-build-v${{ matrix.version }} --all --features pg${{ matrix.version }} --no-default-features
