name: cargo test --all

on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - master

jobs:
  test:

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'nogha')"

    strategy:
      matrix:
        version: [10, 11, 12]
        os: ["ubuntu-latest"]

    steps:
    - uses: actions/checkout@v1

    - name: cargo version
      run: cargo --version

    # Ubuntu system dependencies required to build Postgres from sources
    - name: install postgres build dependencies
      run: sudo apt install -y bison flex zlib1g zlib1g-dev pkg-config libssl-dev

    # install our cargo subcomment
    - name: install cargo pgx
      run: cd cargo-pgx && cargo install --path . --force

    # test our code
    - name: cargo test
      run: RUST_BACKTRACE=1 CARGO_TARGET_DIR=~/cargo-target-dir cargo test --all --features pg${{ matrix.version }} --no-default-features

    # make sure the examples build too
    - name: build arrays example
      run: CARGO_TARGET_DIR=~/cargo-target-dir cd pgx-examples/arrays && cargo test --all --features pg${{ matrix.version }} --no-default-features
    - name: build errors example
      run: CARGO_TARGET_DIR=~/cargo-target-dir cd pgx-examples/errors && cargo test --all --features pg${{ matrix.version }} --no-default-features
    - name: build srf example
      run: CARGO_TARGET_DIR=~/cargo-target-dir cd pgx-examples/srf && cargo test --all --features pg${{ matrix.version }} --no-default-features
    - name: build strings example
      run: CARGO_TARGET_DIR=~/cargo-target-dir cd pgx-examples/strings && cargo pgx test pg${{ matrix.version }}
