name: cargo test --all

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'nogha')"

    strategy:
      matrix:
        version: [10, 11, 12]
        os: ["ubuntu-latest"]

    steps:
    - uses: actions/checkout@v1

    - uses: actions/checkout@v2

    - name: cache cargo pgx init
      id: cargo-pgx-init-cache
      uses: actions/cache@v2
      with:
        path: ~/.pgx/
        key: ${{ matrix.os }}-pgx-init-${{ hashFiles('**/.h') }}

    - name: cargo version
      run: cargo --version

    # Ubuntu system dependencies required to build Postgres from sources
    - name: install postgres build dependencies
      run: sudo apt install -y bison flex zlib1g zlib1g-dev pkg-config libssl-dev libreadline-dev

    # install our cargo subcomment
    - name: install cargo pgx
      if: steps.cargo-pgx-init-cache.outputs.cache-hit != 'true'
      run: cd cargo-pgx && cargo install --path . --force --debug

    # install cargo tree
    - name: install cargo tree
      run: cargo install cargo-tree --debug

    # run cargo tree
    - name: cargo tree
      run: cargo tree

    # initialize pgx
    - name: cargo pgx init
      run: cargo pgx init

    # test our code
    - name: cargo test
      run: RUST_BACKTRACE=1 cargo test --all --features pg${{ matrix.version }} --no-default-features
      env:
        CARGO_TARGET_DIR: ~/target/
